### PR TITLE
Adding a PHING script

### PR DESCRIPTION
**Pull request by javigomez**
I'm modifying the current folder structure and adding a PHING script to generate the package. This will allow also Windows users to generate the package:

Video of the PHING script:
http://youtu.be/gCw6fmw6fmw

I'm going to merge it by my own to avoid you to have many conflicts because i'm rearranging all the files in the component moving them to /component/admin/. Sorry if this cause any inconvenience in your non pulled code.

### CODE REVIEW

**Comment by wilsonge** [comment]
I'm personally not a fan of the restructure. Just because I find it really nice to shove this repo in a joomla install. Add all the joomla folders to the .gitignore and then I can push up any changes I make rather than having to copy them from my test install to somewhere else....

Just my opinion though. A big :+1: for using a phing build script though

**Comment by javigomez** [comment]
Mmm, gotcha! I didn't thought on that. However, I'll be adding tomorrow an extra PHING script that will do what you need: automatically copy all the files to a Joomla installation wherever you have it. Just give me some hours and I will have it ready.

**Comment by javigomez** [comment]
@wilsonge just added a file called copier.xml. Can you check it and confirm that it works for you?

**Comment by phproberto** [comment]
I'm a symbolic link hater because you cannot test installations and if you uninstall files there is a potential risk of deleting repo files. Also there is a chance to add temporal/non needed files to the repo.

Of course not being stupid you can handle that but there is still a risk. 

My personal way is always have a demo site that is updated whenever a file is changed on the main repo. That way the repo is always isolated, you can test the installation whenever you want and assets can be minified automatically on edition with the same build system.

I use [Gulp](http://gulpjs.com/) for that though because it takes care of everything.

**Comment by javigomez** [comment]
closing, since is out of sync. Creating a new one and merging.

@phproberto If you can provide us with a Gulp example file that would be awesome

**Pull request closed without merging**
