### PR TITLE
Add missed sections syntax

### PR DESCRIPTION
**Pull request by Valc**
I forguet add the [ ] when the sections line is mounted. This will solve my mistake.

### CODE REVIEW

**Comment by infograf768** [comment]
@Valc
How do I test this?

**Comment by infograf768** [comment]
OK, found. testing now.

**Comment by Valc** [comment]
I start translating com_localise, that have a lot of sections, and then notice that when saved in normal mode, the sections syntax was crashed.

**Comment by infograf768** [comment]
Confirmed and tested Ok.

**Pull request merged**
