### PR TITLE
[WIP] Remotes

### PR DESCRIPTION
**Pull request by elkuku**
Ref #254

This is an attempt to manage remote repositories for language files.

Currently supported remote types:
- [GitHub](https://github.com)
- [Transifex](https://www.transifex.com)

Example repositories included in this PR:
- **de-DE** from https://github.com/joomlagerman/joomla
- **pt-BR** from https://www.transifex.com/projects/p/j3corelang/

The contents of the repositories will only be fetched, their file names "normalized" and saved to a common file structure.

In a second step (code not included) they can then be compared/replaced with the core files or build the language packages directly from here.
### Info
- http://community.joomla.org/translations/joomla-3-translations.html

See also:
- https://sites.google.com/site/transjoomla/joomla-projects/jcorelang
### Currently this might not work for you because:
1. **Transifex** The `babdev/transifex` library is installed using composer so it is not accessible by the web app (sorry, the CMS ;)).<br />
   **Solution**: Find in `helpers/remotes/Transifex.php` the method `setCredentials()` there is a `require_once()` call that has to be adjusted to your system.
2. **GitHub** The GitHub API implementation included in the CMS has an issue that has been addressed some time ago in newer versions of this library.<br />
   **Solution**: 
   1. Hack the core, find the corresponding package and update the file OR
   2. Update the library (using composer would be nice)

BTW: I did 2.1 so I might describe that in detail if required..
### Testing

After the above is solved you open the remotes view, select the desired remote(s) and click the button `Fetch Remotes`.
A (somewhat ugly) console window should come up, showing the progress of the operation.
When the operation has finished, the files will be in
- `JROOT/administrator/components/com_localise/build/remotes/...`
### Questions
- Is there any name spacing afford currently?
- Can we integrate composer packages?
- How to update the Joomla! GitHub package?

**Thanks!** :wink:

### CODE REVIEW

**Comment by mbabker** [comment]
> Is there any name spacing afford currently?

Within this component or the CMS in general?  If the latter, nothing yet.

> Can we integrate composer packages?

Haven't quite worked out what to do for extensions.  One thing I can think of, which is an ugly hack, is to try and include `libraries/composer_autoload.php` to retrieve the Composer ClassLoader object and add the library path via that API.

> How to update the Joomla! GitHub package?

Send PRs to the CMS repo.  If it means we can dump a lot of the duplicated code between the non-namespaced JGithub and the namespaced Joomla\Github, I'd love to see that happen.

**Comment by elkuku** [comment]
> Is there any name spacing afford currently?
> 
> > Within this component or the CMS in general? If the latter, nothing yet.

Actually I meant the former, as the latter would be far out of scope for the PR....

> One thing I can think of, which is an ugly hack, is to try and include libraries/composer_autoload.php

have a look at https://github.com/elkuku/com_localise/blob/remotes/component/admin/helpers/remotes/Transifex.php#L54-55 :wink: 
Maybe we can add a component parameter to set the absolute path to the `vendor` dir?

> Send PRs to the CMS repo

If we could include the composer package, that'd be great :wink:

**Comment by infograf768** [comment]
far over my head. ;)
One question though.

> When the operation has finished, the files will be in
>   JROOT/administrator/components/com_localise/build/remotes/...

and then what, once they are there (and which files exactly) ?

**Comment by elkuku** [comment]
no interest..

**Pull request closed without merging**
