### PR TITLE
remove unneeded method due to inheritance

### PR DESCRIPTION
**Pull request by javigomez**
This is part of #130

Removes an unneeded method due to inheritance

### CODE REVIEW

**Comment by infograf768** [comment]
javier, I had reverted this from your PR because we could not delete a language.xml anymore

Warning

JFolder: :delete: Path is not a folder. Path: /language/
Error

Error removing languages: /language/

**Comment by infograf768** [comment]
Same issue with translation...
https://github.com/joomla-projects/com_localise/pull/144

**Comment by javigomez** [comment]
mmm, interesting. I will dig on it. Thanks for the warning.

**Comment by phproberto** [comment]
Removing getModel functions disconnects models and controllers so any standard action will be broken. 

My advice: if model exists never remove the method.

**Comment by infograf768** [comment]
Closing for now.

**Pull request closed without merging**
