### PR TITLE
Removed JObject refs #104

### PR DESCRIPTION
**Pull request by Skullbock**

### CODE REVIEW

**Comment by infograf768** [comment]
Testing little by little...
First language xml
Even after correcting the typo here

```
+                                   $copyright = $language->get('copright', array());
```

I can save the copyright field in the xml but it does not display in the edit field.

**Comment by Skullbock** [comment]
Hi @infograf768 can you explain to me how to reproduce? I didn't get it :)

**Comment by infograf768** [comment]
@Skullbock
You would first have to update your branch to develop as I can't show you precise screenshots.

Instructions:
create a language xml for site or admin (NOT installation anymore as we do not display the field)
Add an Author copyright as displayed here:
screen shot 2014-11-13 at 17 38 25

save.

Look at the xx-XX.xml: the Author copyright is righfully added:

```
[...]
    <author>French translation team : joomla.fr</author>
    <authorEmail>traduction@joomla.fr</authorEmail>
    <authorUrl>http://www.joomla.fr</authorUrl>
    <copyright>Copyright (C) 2005 - 2014 Open Source Matters. All rights reserved.</copyright>
    <copyright>Copyright (C) 2005 - 2014 joomla.fr</copyright>
    <license>GNU General Public License version 2 or later; see LICENSE.txt</license>
[...]
```

But the field is empty after save

**Comment by infograf768** [comment]
and we still have the typo in #244 
-                                   $copyright = $language->get('copright', array());

**Comment by Skullbock** [comment]
The issue there is that the xml saves the copyright field twice, and that's not valid for JForm, therefore it doesn't show up correctly.
How should the author and the joomla copyright be managed in the XML? Concatenated or two separate fields?

I'm asking because the code was already there.....

**Comment by Skullbock** [comment]
Fixed typo @ #244

**Comment by infograf768** [comment]
we use the nodes to create 2 `<copyright></copyright>` when the author copyright is added
we have 2 fields in the form:

```
<field
            name="joomlacopyright"
            readonly="true"
            type="text"
            size="50"
            class="ltr"
            label="COM_LOCALISE_LABEL_LANGUAGE_JOOMLACOPYRIGHT"
            description="COM_LOCALISE_LABEL_LANGUAGE_JOOMLACOPYRIGHT_DESC" />
        <field
            name="copyright"
            type="textarea"
            label="COM_LOCALISE_LABEL_LANGUAGE_AUTHORCOPYRIGHT"
            description="COM_LOCALISE_LABEL_LANGUAGE_AUTHORCOPYRIGHT_DESC" />
```

**Comment by Skullbock** [comment]
This should fix it!

**Comment by infograf768** [comment]
can you update this branch to develop? We could separate the github stuff if this PR is OK and merged

**Comment by Skullbock** [comment]
Sorry my fault for using develop instead of a feature branch. I was tired :)

**Comment by infograf768** [comment]
`( ! ) Notice: Undefined property: stdClass::$joomlacopyright in /Applications/MAMP/htdocs/trunkgitnew/administrator/components/com_localise/models/language.php on line 111`

In fact Joomla!™ Copyright should always be present as these are the language xml files, not used by third party

therefore all works fine (for languages) when you take off the conditional
`if (!$data->joomlacopyright) {`

**Comment by infograf768** [comment]
You may also want to solve these:

```
FILE: ...ild/joomla-projects/com_localise/component/admin/models/translation.php

--------------------------------------------------------------------------------

FOUND 1 ERROR(S) AFFECTING 1 LINE(S)

--------------------------------------------------------------------------------

196 | ERROR | Functions and classes must not contain multiple empty lines in a

| | row; found 2 empty lines

--------------------------------------------------------------------------------

FILE: .../build/joomla-projects/com_localise/component/admin/models/language.php

--------------------------------------------------------------------------------

FOUND 1 ERROR(S) AFFECTING 1 LINE(S)

--------------------------------------------------------------------------------

111 | ERROR | Expected "if (...)\n...{...}\n...else\n"; found "if (...)

| | ...{...}\n...else\n"

--------------------------------------------------------------------------------
```

the last one will be solved after you take off the conditional :)

**Comment by infograf768** [comment]
Obsolete

**Pull request closed without merging**
