### PR TITLE
Com_localise with special keys cases 2

### PR DESCRIPTION
**Pull request by Valc**
I have forked the com_localise to show few features than maybe can to be added with improved source code at the main branch.

Here is explained with screenshots what is new:
EDITED LINK
https://github.com/Valc/com_localise/releases/tag/valc-keys-tag

This new pull request have solved by JM few format issues and improvements (tanks).
EDIT:
Here is my list for special string at es-ES and almost all should be common for other languages:

STRINGS TO NOT TRANSLATE:

```
[es-ES]
PLG_DEBUG_QUERY_TYPE_AND_OCCURRENCES="%2$d &#215; %1$s"
PLG_CODEMIRROR_FIELD_VALUE_FULLSCREEN_MOD_ALT="Alt"
PLG_CODEMIRROR_FIELD_VALUE_FULLSCREEN_MOD_CTRL="Control"
PLG_RECAPTCHA_VERSION_1="1.0"
PLG_RECAPTCHA_VERSION_2="2.0"
JLIB_FORM_VALUE_CACHE_REDIS="Redis"
COM_ADMIN_USER_FIELD_EDITOR_LABEL="Editor"
COM_CATEGORIES_TIP_ASSOCIATED_LANGUAGE="%s %s"
COM_CONFIG_FIELD_VALUE_PHP_MAIL="PHP Mail"
COM_CONFIG_FIELD_VALUE_SENDMAIL="Sendmail"
COM_CONFIG_FIELD_VALUE_SMTP="SMTP"
COM_CONFIG_FIELD_VALUE_SSL="SSL"
COM_CONFIG_FIELD_VALUE_TLS="TLS"
COM_CONTACT_FIELD_CONFIG_FAX_LABEL="Fax"
COM_CONTACT_FIELD_CONFIG_VCARD_LABEL="vCard"
COM_CONTACT_FIELD_INFORMATION_FAX_LABEL="Fax"
COM_CONTACT_FIELD_PARAMS_FAX_LABEL="Fax"
COM_CONTACT_FIELD_PARAMS_VCARD_LABEL="vCard"
COM_CONTACT_ID_LABEL="ID"
COM_CONTACT_TIP_ASSOCIATED_LANGUAGE="%s %s (%s)"
COM_CONTACT_CAPTCHA_LABEL="Captcha"
COM_CONTACT_FAX="Fax"
COM_CONTACT_FAX_NUMBER="Fax: %s"
COM_CONTACT_VCARD="vCard"
COM_CONTENT_ID_LABEL="ID"
COM_CONTENT_TIP_ASSOCIATED_LANGUAGE="%s %s (%s)"
COM_CONTENT_CATEGORY_VIEW_BLOG_OPTION="Blog"
COM_FINDER_FIELD_CREATED_BY_ALIAS_LABEL="Alias"
COM_FINDER_STATISTICS_LINK_TYPE_TOTAL="Total"
COM_INSTALLER_HEADING_ID="ID"
COM_INSTALLER_TYPE_PLUGIN="Plugin"
COM_INSTALLER_TYPE_TYPE_PLUGIN="plugin"
COM_LANGUAGES_VIEW_OVERRIDE_LANGUAGE="%1$s [%2$s]"
COM_LANGUAGES_VIEW_OVERRIDES_LANGUAGES_BOX_ITEM="%1$s - %2$s"
COM_MEDIA_IMAGE_TITLE="%1$s - %2$s"
COM_MEDIA_IMAGE_DIMENSIONS="%1$s x %2$s"
COM_MENUS_TIP_ASSOCIATED_LANGUAGE="%s %s (%s)"
COM_MESSAGES_RE="Re:"
COM_MODULES_MODULE_TEMPLATE_POSITION="%1$s (%2$s)"
COM_MODULES_OPTION_ORDER_POSITION="%d. %s"
COM_MODULES_POSITION_SUB1="Sub 1"
COM_MODULES_POSITION_SUB2="Sub 2"
COM_MODULES_POSITION_SUB3="Sub 3"
COM_MODULES_POSITION_SUB4="Sub 4"
COM_MODULES_POSITION_SUB5="Sub 5"
COM_MODULES_POSITION_SUB6="Sub 6"
COM_MODULES_POSITION_SUB="Sub"
COM_NEWSFEEDS_TIP_ASSOCIATED_LANGUAGE="%s %s (%s)"
COM_PLUGINS_PLUGIN="Plugin"
COM_PLUGINS_PLUGINS="Plugins"
COM_POSTINSTALL_TITLE_JOOMLA="Joomla!"
COM_TAGS_FIELD_IMAGE_ALT_LABEL="Alt"
COM_TAGS_TAG_FIELD_MODE_AJAX="AJAX"
COM_TAGS_TAGGED_ITEMS_ID="ID"
COM_TEMPLATES_TAB_EDITOR="Editor"
COM_USERS_CONFIG_FIELD_CAPTCHA_LABEL="Captcha"
COM_USERS_EMPTY_REVIEW="-"
COM_USERS_FIELD_ID_LABEL="ID"
COM_USERS_HEADING_LFT="LFT"
COM_USERS_NOTE_N_SUBJECT="#%d %s"
COM_USERS_USER_FIELD_EDITOR_LABEL="Editor"
COM_USERS_CAPTCHA_LABEL="Captcha"
COM_USERS_USER_FIELD_EDITOR_LABEL="Editor"
COM_WEBLINKS_FIELD_URL_LABEL="URL"
COM_WRAPPER_FIELD_URL_LABEL="URL"
J1="1"
J2="2"
J3="3"
J4="4"
J5="5"
J6="6"
J7="7"
J8="8"
J9="9"
J10="10"
J15="15"
J20="20"
J25="25"
J30="30"
J50="50"
J75="75"
J100="100"
J150="150"
J200="200"
J250="250"
J300="300"
JH1="h1"
JH2="h2"
JH3="h3"
JH4="h4"
JH5="h5"
JH6="h6"
ERROR="Error"
JNO="No"
JBROWSERTARGET_MODAL="Modal"
JEDITOR="Editor"
JERROR_ERROR="Error"
JFIELD_ALIAS_LABEL="Alias"
JFIELD_METADATA_ROBOTS_LABEL="Robots"
JFIELD_SPACER_LABEL="<span style="width:auto"><hr /></span>"
JGLOBAL_BLOG="Blog"
JGLOBAL_FIELD_ID_LABEL="ID"
JGLOBAL_GT="&gt;"
JGLOBAL_ICON_SEP="|"
JGLOBAL_LIST_ALIAS="(<span>Alias</span>: %s)"
JGLOBAL_LT="&lt;"
JGLOBAL_NUM="#"
JGRID_HEADING_ID="ID"
JPAGETITLE="%1$s - %2$s"
DATE_FORMAT_LC="l, d F Y"
DATE_FORMAT_LC1="l, d F Y"
DATE_FORMAT_LC2="l, d F Y H:i"
DATE_FORMAT_LC3="d F Y"
FEBRUARY_SHORT="Feb"
MARCH_SHORT="Mar"
MAY_SHORT="May"
JUNE_SHORT="Jun"
JULY_SHORT="Jul"
SEPTEMBER_SHORT="Sep"
OCTOBER_SHORT="Oct"
NOVEMBER_SHORT="Nov"
DECIMALS_SEPARATOR="."
THOUSANDS_SEPARATOR=","
MYSQL="MySQL"
MYSQLI="MySQLi"
ORACLE="Oracle"
POSTGRESQL="PostgreSQL"
SQLAZURE="Microsoft SQL Azure"
SQLITE="SQLite"
SQLSRV="Microsoft SQL Server"
PDOMYSQL="MySQL (PDO)"
JLIB_FORM_VALUE_CACHE_CACHELITE="Cache_Lite"
JLIB_FORM_VALUE_CACHE_EACCELERATOR="eAccelerator"
JLIB_FORM_VALUE_CACHE_MEMCACHE="Memcache"
JLIB_FORM_VALUE_CACHE_MEMCACHED="Memcached (Experimental)"
JLIB_FORM_VALUE_CACHE_XCACHE="XCache"
JLIB_FORM_VALUE_SESSION_EACCELERATOR="eAccelerator"
JLIB_FORM_VALUE_SESSION_MEMCACHE="Memcache"
JLIB_FORM_VALUE_SESSION_MEMCACHED="Memcached (Experimental)"
JLIB_FORM_VALUE_SESSION_XCACHE="XCache"
JLIB_HTML_ACCESS_MODIFY_DESC_CAPTION_ACL="ACL"
JLIB_HTML_BEHAVIOR_TT_DATE_FORMAT="%a, %b %e"
JLIB_INSTALLER_ABORT_PLG_INSTALL_ROLLBACK="Plugin %1$s: %2$s"
JLIB_RULES_GROUP="%s"
MOD_ARTICLES_ARCHIVE_DATE="%1$s, %2$s"
MOD_ARTICLES_CATEGORY_OPTION_EXCLUSIVE_VALUE="Exclusive"
MOD_ARTICLES_CATEGORY_OPTION_ID_VALUE="ID"
MOD_ARTICLES_CATEGORY_OPTION_INCLUSIVE_VALUE="Inclusive"
MOD_ARTICLES_CATEGORY_OPTION_NORMAL_VALUE="Normal"
MOD_STATS_GZIP="GZip"
MOD_STATS_MYSQL="MySQL"
MOD_STATS_PHP="PHP"
MOD_SYNDICATE_FIELD_VALUE_ATOM="Atom 1.0"
MOD_SYNDICATE_FIELD_VALUE_RSS="RSS 2.0"
MOD_WRAPPER_FIELD_URL_LABEL="URL"
PLG_LDAP_FIELD_V3_LABEL="LDAP V3"
PLG_CAPTCHA_RECAPTCHA="Captcha - ReCaptcha"
PLG_EDITORS_CODEMIRROR="Editor - CodeMirror"
PLG_EDITORS_TINYMCE="Editor - TinyMCE"
PLG_TINY_FIELD_URLS_LABEL="URLs"
PLG_DEBUG_BYTES="Bytes"
PLG_DEBUG_FIELD_LOG_PRIORITIES_ERROR="Error"
PLG_TWOFACTORAUTH_TOTP_STEP1_ITEM1_LINK="http://support.google.com/accounts/bin/answer.py?hl=en&answer=1066447"
PLG_TWOFACTORAUTH_TOTP_STEP1_ITEM2_LINK="http://en.wikipedia.org/wiki/Google_Authenticator#Implementation"
PLG_TWOFACTORAUTH_YUBIKEY_METHOD_TITLE="YubiKey"
TPL_BEEZ3_OPTION_PERSONAL="Personal"
TPL_BEEZ3_SYSTEM_MESSAGE="Error"
COM_INSTALLER_MINIMUM_STABILITY_ALPHA="Alpha"
COM_INSTALLER_MINIMUM_STABILITY_BETA="Beta"
[/es-ES]
```

PROTECTED STRINGS

```
[es-ES]
MOD_MENU_HELP_SUPPORT_OFFICIAL_LANGUAGE_FORUM_VALUE="24"
JHELP_EXTENSIONS_EXTENSION_MANAGER_UPDATESITES="Extensions_Extension_Manager_Updatesites"
JHELP_COMPONENTS_BANNERS_BANNERS_EDIT="Components_Banners_Banners_Edit"
JHELP_COMPONENTS_BANNERS_BANNERS="Components_Banners_Banners"
JHELP_COMPONENTS_BANNERS_CATEGORIES="Components_Banners_Categories"
JHELP_COMPONENTS_BANNERS_CATEGORY_ADD="Components_Banners_Categories_Edit"
JHELP_COMPONENTS_BANNERS_CATEGORY_EDIT="Components_Banners_Categories_Edit"
JHELP_COMPONENTS_BANNERS_CLIENTS_EDIT="Components_Banners_Clients_Edit"
JHELP_COMPONENTS_BANNERS_CLIENTS="Components_Banners_Clients"
JHELP_COMPONENTS_BANNERS_TRACKS="Components_Banners_Tracks"
JHELP_COMPONENTS_CACHE_MANAGER_SETTINGS="Components_Cache_Manager_Settings"
JHELP_COMPONENTS_CHECK-IN_CONFIGURATION="Components_Check-in_Configuration"
JHELP_COMPONENTS_COM_BANNERS_OPTIONS="Components_Banner_Manager_Options"
JHELP_COMPONENTS_COM_CACHE_OPTIONS="Components_Cache_Manager_Settings"
JHELP_COMPONENTS_COM_CHECKIN_OPTIONS="Components_Check_in_Configuration"
JHELP_COMPONENTS_COM_CONTACT_OPTIONS="Components_Contact_Manager_Options"
JHELP_COMPONENTS_COM_CONTENT_OPTIONS="Components_Article_Manager_Options"
JHELP_COMPONENTS_COM_FINDER_OPTIONS="Components_Smart_Search_Configuration"
JHELP_COMPONENTS_COM_INSTALLER_OPTIONS="Components_Installer_Configuration"
JHELP_COMPONENTS_COM_JOOMLAUPDATE_OPTIONS="Components_Joomla_Update_Configuration"
JHELP_COMPONENTS_COM_LANGUAGES_OPTIONS="Components_Language_Manager_Options"
JHELP_COMPONENTS_COM_MEDIA_OPTIONS="Components_Media_Manager_Options"
JHELP_COMPONENTS_COM_MENUS_OPTIONS="Components_Menus_Configuration"
JHELP_COMPONENTS_COM_MESSAGES_OPTIONS="Components_Messages_Configuration"
JHELP_COMPONENTS_COM_MODULES_OPTIONS="Components_Module_Manager_Options"
JHELP_COMPONENTS_COM_NEWSFEEDS_OPTIONS="Components_News_Feed_Manager_Options"
JHELP_COMPONENTS_COM_PLUGINS_OPTIONS="Components_Plug-in_Manager_Options"
JHELP_COMPONENTS_COM_POSTINSTALL_OPTIONS="Components_Post_installation_Messages_Configuration"
JHELP_COMPONENTS_COM_REDIRECT_OPTIONS="Components_Redirect_Manager_Options"
JHELP_COMPONENTS_COM_SEARCH_OPTIONS="Components_Search_Manager_Options"
JHELP_COMPONENTS_COM_TAGS_OPTIONS="Components_Tags_Manager_Options"
JHELP_COMPONENTS_COM_TEMPLATES_OPTIONS="Components_Template_Manager_Options"
JHELP_COMPONENTS_COM_USERS_OPTIONS="Components_Users_Configuration"
JHELP_COMPONENTS_COM_WEBLINKS_OPTIONS="Components_Web_Links_Manager_Options"
JHELP_COMPONENTS_CONTACT_CATEGORIES="Components_Contacts_Categories"
JHELP_COMPONENTS_CONTACT_CATEGORY_ADD="Components_Contacts_Categories_Edit"
JHELP_COMPONENTS_CONTACT_CATEGORY_EDIT="Components_Contacts_Categories_Edit"
JHELP_COMPONENTS_CONTACTS_CONTACTS_EDIT="Components_Contacts_Contacts_Edit"
JHELP_COMPONENTS_CONTACTS_CONTACTS="Components_Contacts_Contacts"
JHELP_COMPONENTS_CONTENT_CATEGORIES="Components_Content_Categories"
JHELP_COMPONENTS_CONTENT_CATEGORY_ADD="Components_Content_Categories_Edit"
JHELP_COMPONENTS_CONTENT_CATEGORY_EDIT="Components_Content_Categories_Edit"
JHELP_COMPONENTS_FINDER_MANAGE_CONTENT_MAPS="Components_Finder_Manage_Content_Maps"
JHELP_COMPONENTS_FINDER_MANAGE_INDEXED_CONTENT="Components_Finder_Manage_Indexed_Content"
JHELP_COMPONENTS_FINDER_MANAGE_SEARCH_FILTERS_EDIT="Components_Finder_Manage_Search_Filters_Edit"
JHELP_COMPONENTS_FINDER_MANAGE_SEARCH_FILTERS="Components_Finder_Manage_Search_Filters"
JHELP_COMPONENTS_INSTALLER_CONFIGURATION="Components_Installer_Configuration"
JHELP_COMPONENTS_JOOMLA_UPDATE="Components_Joomla_Update"
JHELP_COMPONENTS_JOOMLA_UPDATE_CONFIGURATION="Components_Joomla_Update_Configuration"
JHELP_COMPONENTS_MENUS_CONFIGURATION="Components_Menus_Configuration"
JHELP_COMPONENTS_MESSAGES_CONFIGURATION="Components_Messages_Configuration"
JHELP_COMPONENTS_MESSAGING_INBOX="Components_Messaging_Inbox"
JHELP_COMPONENTS_MESSAGING_READ="Components_Messaging_Read"
JHELP_COMPONENTS_MESSAGING_WRITE="Components_Messaging_Write"
JHELP_COMPONENTS_NEWSFEEDS_CATEGORIES="Components_Newsfeeds_Categories"
JHELP_COMPONENTS_NEWSFEEDS_CATEGORY_ADD="Components_Newsfeeds_Categories_Edit"
JHELP_COMPONENTS_NEWSFEEDS_CATEGORY_EDIT="Components_Newsfeeds_Categories_Edit"
JHELP_COMPONENTS_NEWSFEEDS_FEEDS_EDIT="Components_Newsfeeds_Feeds_Edit"
JHELP_COMPONENTS_NEWSFEEDS_FEEDS="Components_Newsfeeds_Feeds"
JHELP_COMPONENTS_POST_INSTALLATION_MESSAGES="Components_Post_installation_Messages"
JHELP_COMPONENTS_REDIRECT_MANAGER_EDIT="Components_Redirect_Manager_Edit"
JHELP_COMPONENTS_REDIRECT_MANAGER="Components_Redirect_Manager"
JHELP_COMPONENTS_SEARCH="Components_Search"
JHELP_COMPONENTS_SMART_SEARCH_CONFIGURATION="Components_Smart_Search_Configuration"
JHELP_COMPONENTS_TAGS_MANAGER="Components_Tags_Manager"
JHELP_COMPONENTS_TAGS_MANAGER_EDIT="Components_Tags_Manager_Edit"
JHELP_COMPONENTS_USERS_CATEGORIES="Users_User_Note_Categories"
JHELP_COMPONENTS_USERS_CATEGORY_ADD="Users_User_Note_Category_Edit"
JHELP_COMPONENTS_USERS_CATEGORY_EDIT="Users_User_Note_Category_Edit"
JHELP_COMPONENTS_WEBLINKS_CATEGORIES="Components_Weblinks_Categories"
JHELP_COMPONENTS_WEBLINKS_CATEGORY_ADD="Components_Weblinks_Categories_Edit"
JHELP_COMPONENTS_WEBLINKS_CATEGORY_EDIT="Components_Weblinks_Categories_Edit"
JHELP_COMPONENTS_WEBLINKS_LINKS_EDIT="Components_Weblinks_Links_Edit"
JHELP_COMPONENTS_WEBLINKS_LINKS="Components_Weblinks_Links"
JHELP_CONTENT_ARTICLE_MANAGER="Content_Article_Manager"
JHELP_CONTENT_ARTICLE_MANAGER_EDIT="Content_Article_Manager_Edit"
JHELP_CONTENT_FEATURED_ARTICLES="Content_Featured_Articles"
JHELP_CONTENT_MEDIA_MANAGER="Content_Media_Manager"
JHELP_EXTENSIONS_EXTENSION_MANAGER_DATABASE="Extensions_Extension_Manager_Database"
JHELP_EXTENSIONS_EXTENSION_MANAGER_DISCOVER="Extensions_Extension_Manager_Discover"
JHELP_EXTENSIONS_EXTENSION_MANAGER_INSTALL="Extensions_Extension_Manager_Install"
JHELP_EXTENSIONS_EXTENSION_MANAGER_LANGUAGES="Extensions_Extension_Manager_languages"
JHELP_EXTENSIONS_EXTENSION_MANAGER_MANAGE="Extensions_Extension_Manager_Manage"
JHELP_EXTENSIONS_EXTENSION_MANAGER_UPDATE="Extensions_Extension_Manager_Update"
JHELP_EXTENSIONS_EXTENSION_MANAGER_WARNINGS="Extensions_Extension_Manager_Warnings"
JHELP_EXTENSIONS_LANGUAGE_MANAGER_CONTENT="Extensions_Language_Manager_Content"
JHELP_EXTENSIONS_LANGUAGE_MANAGER_EDIT="Extensions_Language_Manager_Edit"
JHELP_EXTENSIONS_LANGUAGE_MANAGER_INSTALLED="Extensions_Language_Manager_Installed"
JHELP_EXTENSIONS_LANGUAGE_MANAGER_OVERRIDES="Extensions_Language_Manager_Overrides"
JHELP_EXTENSIONS_LANGUAGE_MANAGER_OVERRIDES_EDIT="Extensions_Language_Manager_Overrides_Edit"
JHELP_EXTENSIONS_MODULE_MANAGER="Extensions_Module_Manager"
JHELP_EXTENSIONS_MODULE_MANAGER_ADMIN_CUSTOM="Extensions_Module_Manager_Admin_Custom"
JHELP_EXTENSIONS_MODULE_MANAGER_ADMIN_FEED="Extensions_Module_Manager_Admin_Feed"
JHELP_EXTENSIONS_MODULE_MANAGER_ADMIN_LATEST="Extensions_Module_Manager_Admin_Latest"
JHELP_EXTENSIONS_MODULE_MANAGER_ADMIN_LOGGED="Extensions_Module_Manager_Admin_Logged"
JHELP_EXTENSIONS_MODULE_MANAGER_ADMIN_LOGIN="Extensions_Module_Manager_Admin_Login"
JHELP_EXTENSIONS_MODULE_MANAGER_ADMIN_MENU="Extensions_Module_Manager_Admin_Menu"
JHELP_EXTENSIONS_MODULE_MANAGER_ADMIN_MULTILANG="Extensions_Module_Manager_Admin_Multilang"
JHELP_EXTENSIONS_MODULE_MANAGER_ADMIN_ONLINE="Extensions_Module_Manager_Admin_Online"
JHELP_EXTENSIONS_MODULE_MANAGER_ADMIN_POPULAR="Extensions_Module_Manager_Admin_Popular"
JHELP_EXTENSIONS_MODULE_MANAGER_ADMIN_QUICKICON="Extensions_Module_Manager_Admin_Quickicon"
JHELP_EXTENSIONS_MODULE_MANAGER_ADMIN_STATUS="Extensions_Module_Manager_Admin_Status"
JHELP_EXTENSIONS_MODULE_MANAGER_ADMIN_SUBMENU="Extensions_Module_Manager_Admin_Submenu"
JHELP_EXTENSIONS_MODULE_MANAGER_ADMIN_TITLE="Extensions_Module_Manager_Admin_Title"
JHELP_EXTENSIONS_MODULE_MANAGER_ADMIN_TOOLBAR="Extensions_Module_Manager_Admin_Toolbar"
JHELP_EXTENSIONS_MODULE_MANAGER_ADMIN_UNREAD="Extensions_Module_Manager_Admin_Unread"
JHELP_EXTENSIONS_MODULE_MANAGER_ARTICLES_ARCHIVE="Extensions_Module_Manager_Articles_Archive"
JHELP_EXTENSIONS_MODULE_MANAGER_ARTICLES_CATEGORIES="Extensions_Module_Manager_Articles_Categories"
JHELP_EXTENSIONS_MODULE_MANAGER_ARTICLES_CATEGORY="Extensions_Module_Manager_Articles_Category"
JHELP_EXTENSIONS_MODULE_MANAGER_ARTICLES_NEWSFLASH="Extensions_Module_Manager_Articles_Newsflash"
JHELP_EXTENSIONS_MODULE_MANAGER_ARTICLES_RELATED="Extensions_Module_Manager_Articles_Related"
JHELP_EXTENSIONS_MODULE_MANAGER_BANNERS="Extensions_Module_Manager_Banners"
JHELP_EXTENSIONS_MODULE_MANAGER_BREADCRUMBS="Extensions_Module_Manager_Breadcrumbs"
JHELP_EXTENSIONS_MODULE_MANAGER_CUSTOM_HTML="Extensions_Module_Manager_Custom_HTML"
JHELP_EXTENSIONS_MODULE_MANAGER_EDIT="Extensions_Module_Manager_Edit"
JHELP_EXTENSIONS_MODULE_MANAGER_FEED_DISPLAY="Extensions_Module_Manager_Feed_Display"
JHELP_EXTENSIONS_MODULE_MANAGER_FOOTER="Extensions_Module_Manager_Footer"
JHELP_EXTENSIONS_MODULE_MANAGER_LANGUAGE_SWITCHER="Extensions_Module_Manager_Language_Switcher"
JHELP_EXTENSIONS_MODULE_MANAGER_LATEST_NEWS="Extensions_Module_Manager_Latest_News"
JHELP_EXTENSIONS_MODULE_MANAGER_LATEST_USERS="Extensions_Module_Manager_Latest_Users"
JHELP_EXTENSIONS_MODULE_MANAGER_LOGIN="Extensions_Module_Manager_Login"
JHELP_EXTENSIONS_MODULE_MANAGER_MENU="Extensions_Module_Manager_Menu"
JHELP_EXTENSIONS_MODULE_MANAGER_MOST_READ="Extensions_Module_Manager_Most_Read"
JHELP_EXTENSIONS_MODULE_MANAGER_RANDOM_IMAGE="Extensions_Module_Manager_Random_Image"
JHELP_EXTENSIONS_MODULE_MANAGER_SEARCH="Extensions_Module_Manager_Search"
JHELP_EXTENSIONS_MODULE_MANAGER_SMART_SEARCH="Extensions_Module_Manager_Smart_Search"
JHELP_EXTENSIONS_MODULE_MANAGER_STATISTICS="Extensions_Module_Manager_Statistics"
JHELP_EXTENSIONS_MODULE_MANAGER_SYNDICATION_FEEDS="Extensions_Module_Manager_Syndication_Feeds"
JHELP_EXTENSIONS_MODULE_MANAGER_TAGS_POPULAR="Extensions_Module_Manager_Tags_Popular"
JHELP_EXTENSIONS_MODULE_MANAGER_TAGS_SIMILAR="Extensions_Module_Manager_Tags_Similar"
JHELP_EXTENSIONS_MODULE_MANAGER_WEBLINKS="Extensions_Module_Manager_Weblinks"
JHELP_EXTENSIONS_MODULE_MANAGER_WHO_ONLINE="Extensions_Module_Manager_Who_Online"
JHELP_EXTENSIONS_MODULE_MANAGER_WRAPPER="Extensions_Module_Manager_Wrapper"
JHELP_EXTENSIONS_PLUGIN_MANAGER="Extensions_Plugin_Manager"
JHELP_EXTENSIONS_PLUGIN_MANAGER_EDIT="Extensions_Plugin_Manager_Edit"
JHELP_EXTENSIONS_TEMPLATE_MANAGER_STYLES="Extensions_Template_Manager_Styles"
JHELP_EXTENSIONS_TEMPLATE_MANAGER_STYLES_EDIT="Extensions_Template_Manager_Styles_Edit"
JHELP_EXTENSIONS_TEMPLATE_MANAGER_TEMPLATES="Extensions_Template_Manager_Templates"
JHELP_EXTENSIONS_TEMPLATE_MANAGER_TEMPLATES_EDIT="Extensions_Template_Manager_Templates_Edit"
JHELP_EXTENSIONS_TEMPLATE_MANAGER_TEMPLATES_EDIT_SOURCE="Extensions_Template_Manager_Templates_Edit_Source"
JHELP_GLOSSARY="Glossary"
JHELP_MENUS_MENU_ITEM_ARTICLE_ARCHIVED="Menus_Menu_Item_Article_Archived"
JHELP_MENUS_MENU_ITEM_ARTICLE_CATEGORIES="Menus_Menu_Item_Article_Categories"
JHELP_MENUS_MENU_ITEM_ARTICLE_CATEGORY_BLOG="Menus_Menu_Item_Article_Category_Blog"
JHELP_MENUS_MENU_ITEM_ARTICLE_CATEGORY_LIST="Menus_Menu_Item_Article_Category_List"
JHELP_MENUS_MENU_ITEM_ARTICLE_CREATE="Menus_Menu_Item_Article_Create"
JHELP_MENUS_MENU_ITEM_ARTICLE_FEATURED="Menus_Menu_Item_Article_Featured"
JHELP_MENUS_MENU_ITEM_ARTICLE_SINGLE_ARTICLE="Menus_Menu_Item_Article_Single_Article"
JHELP_MENUS_MENU_ITEM_CONTACT_CATEGORIES="Menus_Menu_Item_Contact_Categories"
JHELP_MENUS_MENU_ITEM_CONTACT_CATEGORY="Menus_Menu_Item_Contact_Category"
JHELP_MENUS_MENU_ITEM_CONTACT_FEATURED="Menus_Menu_Item_Contact_Featured"
JHELP_MENUS_MENU_ITEM_CONTACT_SINGLE_CONTACT="Menus_Menu_Item_Contact_Single_Contact"
JHELP_MENUS_MENU_ITEM_DISPLAY_SITE_CONFIGURATION="Menus_Menu_Item_Display_Site_Configuration"
JHELP_MENUS_MENU_ITEM_DISPLAY_TEMPLATE_OPTIONS="Menus_Menu_Item_Display_Template_Options"
JHELP_MENUS_MENU_ITEM_EXTERNAL_URL="Menus_Menu_Item_External_URL"
JHELP_MENUS_MENU_ITEM_FINDER_SEARCH="Menus_Menu_Item_Finder_Search"
JHELP_MENUS_MENU_ITEM_MANAGER="Menus_Menu_Item_Manager"
JHELP_MENUS_MENU_ITEM_MANAGER_EDIT="Menus_Menu_Item_Manager_Edit"
JHELP_MENUS_MENU_ITEM_MENU_ITEM_ALIAS="Menus_Menu_Item_Menu_Item_Alias"
JHELP_MENUS_MENU_ITEM_MENU_ITEM_HEADING="Menus_Menu_Item_Menu_Item_Heading"
JHELP_MENUS_MENU_ITEM_NEWSFEED_CATEGORIES="Menus_Menu_Item_Newsfeed_Categories"
JHELP_MENUS_MENU_ITEM_NEWSFEED_CATEGORY="Menus_Menu_Item_Newsfeed_Category"
JHELP_MENUS_MENU_ITEM_NEWSFEED_SINGLE_NEWSFEED="Menus_Menu_Item_Newsfeed_Single_Newsfeed"
JHELP_MENUS_MENU_ITEM_SEARCH_RESULTS="Menus_Menu_Item_Search_Results"
JHELP_MENUS_MENU_ITEM_TAGS_ITEMS_COMPACT_LIST="Menus_Menu_Item_Tags_Items_Compact_List"
JHELP_MENUS_MENU_ITEM_TAGS_ITEMS_LIST="Menus_Menu_Item_Tags_Items_List"
JHELP_MENUS_MENU_ITEM_TAGS_ITEMS_LIST_ALL="Menus_Menu_Item_Tags_Items_List_All"
JHELP_MENUS_MENU_ITEM_TEXT_SEPARATOR="Menus_Menu_Item_Text_Separator"
JHELP_MENUS_MENU_ITEM_USER_LOGIN="Menus_Menu_Item_User_Login"
JHELP_MENUS_MENU_ITEM_USER_PASSWORD_RESET="Menus_Menu_Item_User_Password_Reset"
JHELP_MENUS_MENU_ITEM_USER_PROFILE="Menus_Menu_Item_User_Profile"
JHELP_MENUS_MENU_ITEM_USER_PROFILE_EDIT="Menus_Menu_Item_User_Profile_Edit"
JHELP_MENUS_MENU_ITEM_USER_REGISTRATION="Menus_Menu_Item_User_Registration"
JHELP_MENUS_MENU_ITEM_USER_REMINDER="Menus_Menu_Item_User_Reminder"
JHELP_MENUS_MENU_ITEM_WEBLINK_CATEGORIES="Menus_Menu_Item_Weblink_Categories"
JHELP_MENUS_MENU_ITEM_WEBLINK_CATEGORY="Menus_Menu_Item_Weblink_Category"
JHELP_MENUS_MENU_ITEM_WEBLINK_SUBMIT="Menus_Menu_Item_Weblink_Submit"
JHELP_MENUS_MENU_ITEM_WRAPPER="Menus_Menu_Item_Wrapper"
JHELP_MENUS_MENU_MANAGER="Menus_Menu_Manager"
JHELP_MENUS_MENU_MANAGER_EDIT="Menus_Menu_Manager_Edit"
JHELP_SITE_GLOBAL_CONFIGURATION="Site_Global_Configuration"
JHELP_SITE_MAINTENANCE_CLEAR_CACHE="Site_Maintenance_Clear_Cache"
JHELP_SITE_MAINTENANCE_GLOBAL_CHECK-IN="Site_Maintenance_Global_Check-in"
JHELP_SITE_MAINTENANCE_PURGE_EXPIRED_CACHE="Site_Maintenance_Purge_Expired_Cache"
JHELP_SITE_SYSTEM_INFORMATION="Site_System_Information"
JHELP_ADMIN_USER_PROFILE_EDIT="Site_My_Profile"
JHELP_START_HERE="Start_Here"
JHELP_USERS_ACCESS_LEVELS="Users_Access_Levels"
JHELP_USERS_ACCESS_LEVELS_EDIT="Users_Access_Levels_Edit"
JHELP_USERS_DEBUG_GROUPS="Users_Debug_Groups"
JHELP_USERS_DEBUG_USERS="Users_Debug_Users"
JHELP_USERS_GROUPS="Users_Groups"
JHELP_USERS_GROUPS_EDIT="Users_Groups_Edit"
JHELP_USERS_MASS_MAIL_USERS="Users_Mass_Mail_Users"
JHELP_USERS_USER_MANAGER="Users_User_Manager"
JHELP_USERS_USER_MANAGER_EDIT="Users_User_Manager_Edit"
JHELP_USERS_USER_NOTES="Users_User_Notes"
JHELP_USERS_USER_NOTES_EDIT="Users_User_Notes_Edit"
[/es-ES]
```

Regards, Valc

### CODE REVIEW

**Comment by Valc** [comment]
Hi, JM:
After your last commit i have been trying to improve the amout of code lines to use and the detected 'scrutinizer' issues.
Now seem that travis is also ok, and i am close to my limit "improving" in Joomla way, but let me know if i can help doing something more.

Regards, Valc.

**Comment by infograf768** [comment]
@Valc

Our priority for now is: https://github.com/joomla-projects/com_localise/pull/260

As it will require an update in your branch, I prefer to wait for this one.

**Comment by infograf768** [comment]
@Valc 
Look at this idea I had that would make it much easier to tick as Special in the translation edit screen.
https://github.com/joomla-projects/com_localise/issues/264#issuecomment-72805622

**Comment by Valc** [comment]
Done :)
https://github.com/joomla-projects/com_localise/issues/264#issuecomment-73084270

**Comment by infograf768** [comment]
@valc
Is it possible to add in the "Localisation Manager: Edit translation" => Strings tab page a filter to filter by status (unchanged, translated, etc.) ?

**Comment by Valc** [comment]
```
@valc
Is it possible to add in the "Localisation Manager: Edit translation" => Strings tab page a filter to filter by status (unchanged, translated, etc.) ?
```

This sounds great: i can try to do a test this weekend due i have samples about other filters working within com_localise.

If i am not able to follow how is working i will comment about my limit.

Regards.

**Comment by infograf768** [comment]
Obsolete

**Pull request closed without merging**
