### PR TITLE
Improve speed loading translations list

### PR DESCRIPTION
**Pull request by fastslack**
After a better code review, reached the conclusion that ajax loading is not required. With this patch, we improve the list loading allowing progressive cache and db savings.

### CODE REVIEW

**Comment by javigomez** [comment]
suuuper! thanks @fastslack. I'll test.

cc: @infograf768

**Comment by fastslack** [comment]
@javigomez :) Sorry about the delay

**Comment by infograf768** [comment]
Testing now

**Comment by infograf768** [comment]
I see no apparent error here.
Some code style: missing spaces before \* in comments

```
FILE: ...ld/joomla-projects/com_localise/component/admin/models/translations.php

--------------------------------------------------------------------------------

FOUND 7 ERROR(S) AFFECTING 7 LINE(S)

--------------------------------------------------------------------------------

714 | ERROR | Expected 2 space(s) before asterisk; 1 found

715 | ERROR | Expected 2 space(s) before asterisk; 1 found

716 | ERROR | Expected 2 space(s) before asterisk; 1 found

717 | ERROR | Expected 2 space(s) before asterisk; 1 found

718 | ERROR | Expected 2 space(s) before asterisk; 1 found

719 | ERROR | Expected 2 space(s) before asterisk; 1 found

720 | ERROR | Expected 2 space(s) before asterisk; 1 found

```

As I did not have here any issue before, how could I test the speed increase?

**Comment by infograf768** [comment]
Wanted to use debug to see speed, but I get (in view=languages):
( ! ) Fatal error: Allowed memory size of 138412032 bytes exhausted (tried to allocate 3472221 bytes) in /Applications/MAMP/htdocs/trunkgitnew/plugins/system/debug/debug.php on line 1109
reloading page displays all languages (had used Purge Database before).

When using debug and going to view=translations, same error in log but page is blank

**Comment by javigomez** [comment]
@fastslack please check my pull https://github.com/fastslack/com_localise/pull/4 to your branch fixing the code style issues.

**Comment by fastslack** [comment]
@infograf768 looking the memory issue using Joomla! debug. If you dont use debug, the list load without problems?

@javigomez the patch works fine for you? i mean, increase the speed?

**Comment by infograf768** [comment]
Without debug, list loads fine (debug issue was same before patch anyway). Was just trying to figure speed increase

**Comment by infograf768** [comment]
I have set my memory limit to a "normal" 32Mb ( I had 132Mb) and the patch does not work at all (debug off):
I get
Fatal error: Allowed memory size of 33554432 bytes exhausted (tried to allocate 29852 bytes) in /Applications/MAMP/htdocs/trunkgitnew/administrator/components/com_localise/helpers/localise.php on line 634

**Comment by infograf768** [comment]
Further tests:
If I get rid of the parseSections() calls, It works again but I have to limit the list to 50 max
If I go further (3 real languages + the languages included in com_localise as ), I then get another memory limit:
Fatal error: Allowed memory size of 33554432 bytes exhausted (tried to allocate 282522 bytes) in /Applications/MAMP/htdocs/trunkgitnew/libraries/joomla/application/web.php on line 723

Looks also that we have another bug (before this PR):
When an xml does not exist for the administrator client (in my case it is administrator because com_localise files are present in administrator language folders), core translations should not be proposed. Here, as we have for example da-DK as a com_localise file copied to main folder, we do get all da-DK proposed for administrator. We have to look into that one.

**Comment by infograf768** [comment]
For the last issue, please test:
https://github.com/joomla-projects/com_localise/pull/190

**Pull request closed without merging**
