### PR TITLE
Adding PHP Mess Detector to travis

### PR DESCRIPTION
**Pull request by javigomez**
Adds PHP Mess Detector, that will give us automated interesting advises to improve the code.

### CODE REVIEW

**Comment by wilsonge** [comment]
So I think there are a few issues with this. Mainly that it makes travis fail because we have unused variables (which is always gonna happen with the mvc structure of joomla (new or legacy)). Plus `$id` is not at least 3 chars long which is just barmy

http://docs.travis-ci.com/user/build-configuration/ This talks about allowing things to fail and it would be nice if we could have this but allow it to fail. So we have the pointers but don't have to implement all of them.

**Comment by javigomez** [comment]
I have removed the Naming checker http://phpmd.org/rules/naming.html

Actually we can create our own ruleset: http://phpmd.org/documentation/creating-a-ruleset.html

**Comment by javigomez** [comment]
maybe we can convert the call into a PHP script that returns the output and exits with 0

Something like Michael did with PHPcs

**Comment by javigomez** [comment]
Now works:

screen shot 2014-07-06 at 15 29 57

...

screen shot 2014-07-06 at 15 30 08

^_^

**Comment by javigomez** [comment]
Thanks @wilsonge  ^_^

**Pull request merged**
