### PR TITLE
Com Localise with special keys cases

### PR DESCRIPTION
**Pull request by Valc**
I have forked the com_localise to show few features than maybe can to be added with improved source at the main branch. 
Here is explained with screenshots what is new:
https://github.com/Valc/com_localise/releases/tag/4.0.8-dev_by_valc

Regards, Valc

### CODE REVIEW

**Comment by infograf768** [comment]
@Valc
Is this version 3 I got in the forum? If yes, see my comments there.
Also:
Careful please with formatting. We follow Joomla formatting.
for example:

```
        $regex_syntax   = '/\['.$target_tag.'\](.*?)\[\/'.$target_tag.'\]/s';

            if (preg_match($regex_syntax, $global_blockedkeys))
            {
            preg_match_all($regex_syntax, $global_blockedkeys, $blockedkeys_block, PREG_SET_ORDER);
            $blockedkeys = preg_split( '/\r\n|\r|\n/', $blockedkeys_block[0][1]);

            } else {
            $blockedkeys = array();
            }
```

should be (invisible spaces, tabs and returns displaying):
screen shot 2015-01-24 at 19 14 33

**Comment by infograf768** [comment]
@Valc 
I have corrected the path to the codemirror files in staging. Source editing should now work fine.
https://github.com/joomla-projects/com_localise/commit/08805c0019d4d1de5007e5c91c21f9d0d3907148

You will have to update your branch

**Comment by infograf768** [comment]
Concerning usergroup access to source edit, I suggest you rather deal with it the same way we do for the debug plugin, i.e allow all except if specific groups are entered.
See isAuthorisedDisplayDebug()
`PLG_DEBUG_FIELD_ALLOWED_GROUPS_DESC="Optionally restrict users that can see debug information to those in the selected user groups. If none selected, all users see the debug information."
`

**Comment by Valc** [comment]
Hi, JM:
Seems that the new commits are displayed also here.
I have modiffied all what you have commented before and for me is working.

Also i have added an "v4" package with last changes update:

https://github.com/Valc/com_localise/releases/tag/4.0.8-dev_by_valc

I dont understand at all the red "x" that are showed over few files.

Reading the "travis report" i can to found a lot of reports talking about "camelCases" that are not related only with my variables, so i am a bit lost there due the big output that is displayed.

I have added you to my fork due maybe you can resolve that stuff than for me are hard to found in this moment due i am not familiarised with Github.

The next week i am out of home again and maybe you need access there to edit stuff or similar.

Regards, Valc.

**Comment by infograf768** [comment]
@Valc
I have now updated com_localise to 4.0.9-dev to cope with the codemirror issue as we freeze languages tomorrow to prepare 3.4.0 release.
This means that you have to update your branch (and not merge into it the changes as you did for https://github.com/joomla-projects/com_localise/commit/08805c0019d4d1de5007e5c91c21f9d0d3907148 )

I see indeed many errors in Travis which are quite easy to solve.
One we should not have is the one related to length of line 239 of translation.php
`$global_untranslatablekeys = $params->get('untranslatablekeys', '[xx-XX]&#xA;COM_CATEGORIES_TIP_ASSOCIATED_LANGUAGE=&quot;%s %s&quot;&#xA;COM_CONTACT_TIP_ASSOCIATED_LANGUAGE=&quot;%s %s (%s)&quot;&#xA;COM_CONTENT_TIP_ASSOCIATED_LANGUAGE=&quot;%s %s (%s)&quot;&#xA;COM_LANGUAGES_VIEW_OVERRIDE_LANGUAGE=&quot;%1$s [%2$s]&quot;&#xA;COM_LANGUAGES_VIEW_OVERRIDES_LANGUAGES_BOX_ITEM=&quot;%1$s - %2$s&quot;&#xA;COM_MEDIA_IMAGE_TITLE=&quot;%1$s - %2$s&quot;&#xA;COM_MEDIA_IMAGE_DIMENSIONS=&quot;%1$s x %2$s&quot;&#xA;COM_MENUS_TIP_ASSOCIATED_LANGUAGE=&quot;%s %s (%s)&quot;&#xA;COM_NEWSFEEDS_TIP_ASSOCIATED_LANGUAGE=&quot;%s %s (%s)&quot;&#xA;COM_POSTINSTALL_TITLE_JOOMLA=&quot;Joomla!&quot;&#xA;COM_USERS_EMPTY_REVIEW=&quot;-&quot;&#xA;COM_USERS_NOTE_N_SUBJECT=&quot;#%d %s&quot;&#xA;JGLOBAL_GT=&quot;&gt;&quot;&#xA;JGLOBAL_ICON_SEP=&quot;|&quot;&#xA;JGLOBAL_NUM=&quot;#&quot;&#xA;JPAGETITLE=&quot;%1$s - %2$s&quot;&#xA;DECIMALS_SEPARATOR=&quot;.&quot;&#xA;THOUSANDS_SEPARATOR=&quot;,&quot;&#xA;JLIB_RULES_GROUP=&quot;%s&quot;&#xA;[/xx-XX]&#xA;');
`
We just should NOT have so many examples there... 
Instead, you should use a text displaying over the label and field to give some examples 2 may be enough) + the description of the field to help

Also
`$contents .= ";This keys are not present in en-GB language but are required in this language (extra plural cases, custom CAPTCHA translations, etc).\n\n";
`
This should be a lang constant and new language string.

Also you have not corrected the other errors with if else and spaces before and after a parenthesis.

(leave the camel case alone, not important for now)

**Comment by Valc** [comment]
Last pack is here now:
https://github.com/Valc/com_localise/releases/tag/last_com_localise_released_by_valc
I dont understand how to set the commented line about keys to delete in a constant or in a new string, or from where to do that.

All the "if" that i can read within files that i have edited have an space before the parenthesis. is this wrong for all cases or only for the mine?

The other one seems is done.

**Comment by infograf768** [comment]
@Valc
We do not need you post last pack.
We can patch an existing local git repository with this PR .diff

If I have time today, I will make a new branch of mine where I will try to correct the format.

**Comment by infograf768** [comment]
Please see
https://github.com/joomla-projects/com_localise/pull/258

If you like, just create a new branch, apply 258, make a new PR  and let's start from there.
There are quite a few things I have not corrected.

**Comment by Valc** [comment]
Ok, thank you for your help.

**Comment by infograf768** [comment]
Replaced by https://github.com/joomla-projects/com_localise/pull/259

**Pull request closed without merging**
