### PR TITLE
Fixes checkin-checkout behavior for languages, translations.

### PR DESCRIPTION
**Pull request by Achal-Aggarwal**
Currently languages &  translations are working for me. 
thanks @infograf768 for testing it again and again and again.

Note :- I'll make separate PR for packages.

### CODE REVIEW

**Comment by infograf768** [comment]
Errors when creating new language.

**Comment by Achal-Aggarwal** [comment]
I am passing config param directly to avoid re-populating the state of the model. I tested this change and it doesn't break anything at my site.

If it break anything for anyone we can have another look for its correct usage.

**Comment by infograf768** [comment]
Working fine now. Remains to do it for packages.

**Comment by Achal-Aggarwal** [comment]
For packages : https://github.com/joomla-projects/com_localise/pull/213

**Pull request merged**
