### PR TITLE
This is Matias pull for AJAX loading files

### LINKED ISSUE #44: Fix performance issues
Currently the first load of com_localise starts processes all the .ini causing very poor performance. In some servers you get timeouts.

We need to study the current component and find a solution that makes it more performant. Maybe the solution could be an AJAX view that processes step by step all the things that needs to be done.

### PR DESCRIPTION
**Pull request by javigomez**
# Please do not merge this pull, this is work in progress

@fastslack I'm creating this pull so we can discuss it here and improve it before we can merge it.

This pull was started to fix https://github.com/joomla-projects/com_localise/issues/44

### CODE REVIEW

**Comment by javigomez** [comment]
@fastslack after merging my pull, I have tested and I'm getting now this new error:

screen shot 2014-07-06 at 17 04 30

**Comment by javigomez** [comment]
@fastslack while testing I found some code style issues. I'm not sure about my dockblock fixes. Please have a look and say what you think: https://github.com/fastslack/com_localise/pull/3

Thanks very much ^_^

**Comment by infograf768** [comment]
For now, this code is only a demo. If I understand well it should be applied to the translations view or any existing view for update and not to a specific Load view. If I mistake please explain.

**Comment by javigomez** [comment]
yes, I fully agree. This load view is just an example of how to call the AJAX function that loads step by step the INI strings. After we make it work we need to refactor the translations view.

**Comment by fastslack** [comment]
@javigomez Please check this PR https://github.com/joomla-projects/com_localise/pull/189

Seems that ajax loading is not required, with that PR we improve the lists loading significantly.

**Comment by javigomez** [comment]
closing in front of #189

**Pull request closed without merging**
