### PR TITLE
Improve travis tests: test other php versions (5.6, 7 and hhvm); run code style tests only on one php version

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Check code difference

I'm not sure is anything else is needed.

the patchtester travis.yml is a little different reggarding CS
See https://github.com/joomla-extensions/patchtester/blob/master/.travis.yml

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
it seems something more is needed because travis did not run on this PR

**Comment by mbabker** [comment]
Since you're not actually using the `RUN_PHPCS` global you don't need to define it.  Otherwise, the test scripts are set up here differently than they are in the patchtester repo so not much else I can say on that.

**Comment by andrepereiradasilva** [comment]
ok thanks @mbabker 
It's now testing on php 5.6 and php 7 too

**Comment by andrepereiradasilva** [comment]
Guess what: it pass the php 7 test :)

**Comment by infograf768** [comment]
I honestly have no idea if this should be merged or not.
@javigomez , please decide.

**Comment by javigomez** [comment]
I see we are currently not running the system tests in travis so should not affect. Checking the builds after George's merge seems all to work okay.

**Pull request merged**
