### PR TITLE
Breaking Joomla Installation, Extension Installation to Smaller Step Objects in Codeception

### PR DESCRIPTION
**Pull request by puneet0191**
This PR breaks Joomla Installation into smaller steps, and updates the step clases names along with some extra fields being added to the Page Objects for Installation Class @javigomez Kindly review the PR and merge it if you feel this is the correct way

### CODE REVIEW

**Comment by infograf768** [comment]
Could you explain to me what this has to do with com_localise?

**Comment by puneet0191** [comment]
@infograf768 This PR is related to System Testing part for the extension, me and Javier have been working on that, I wanted to update the current step clases hence I submitted a PR

**Comment by javigomez** [comment]
@infograf768 this files create a webserver in Travis and create a Joomla CMS instance, then installs com_localise and check that everything works finally uninstalls com_localise. If any future pull break any of the com_localise screens, the installer or the uninstaller we will get a warning from travis. I did a small presentation at JWC14 about it, you can find it here: http://prezi.com/qsf17leurgbe/automated-system-testing-in-joomla/

If you want we can meet at skype and I can show it to you.

**Comment by javigomez** [comment]
Setting up documentation is available here: https://github.com/joomla-projects/com_localise/blob/develop/README.md#testing-with-codeception

**Comment by wilsonge** [comment]
Tests pass and it only affects your codeception stuff so merging this

**Pull request merged**
